version: "3.8"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - "3306:3306"
